---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgCxTLs3B4pXjscF861wEtkFU1ab/eqy22/SSvdzHW0MLnF3FDYLq1I7N3SqK8WxEzssbcCGieASC5W7bvsMFY3RceNt7C9nb8a8X8LwfD/yktryAhf93k+0LFpbDA4KqnMHu6zL5j39OMlCaSnDK6I2AgzQIr22akiYeOjnE4pGu9H4yfo1nDqbyx2K0XiB5hHfR1xPuVXNqXEvFpPv0HqJ9aEqADzEHx4GwBIX38eoV1cYOENq54rao0cd5oDjA+jqdbuFj4GGmkP8Z77HA0f4wHBsQ9tZZB1Pea1G39NBILx/XAt6W8iAUalBBe3rqvQMVmSMzfRmFbchUv3DbppnO0agsULp/sPYy61K97uirB+4AHodtQBL6eQC41zWf9Rha5H6W03Aq9PgBVK04VaHtfHuuxm4K2JZIJfOS82eaHDOWU4wFACWE1Sjy/w/BQNpyfIgsFQIUry9tF+3EUv9GI/Z+VcQnx5l2D9T2hnTqgke/Kn6dtpth2uv03U3Onpa8h6Pqg07X4UwM2AthUQDNhvfEfZrOApV9Lq+qJed229XlSE5fz6a5gtXA3gezOH/Hie17qsIOCwWeVh28pwCyo2v4IlQDBjU8n3WsAByxy7YKcRCbKWeNAVBlvyBDu8yJKwNkryPsqzOfLPmGV5GljjrazZZavm7qMc0b2poyheEstm0lRSsD99czZDKgdPqJiw1rADT
    username: AgCQaBR7T2X6Ci4mSyvGNQu6/ElzFd+GbVU2YqbSF8AqT0VX9TwjK8nCkD6pIKWnMRxSyzYO/BXGIvxaimYAm4jkRzQZfOaG2dwrYN5UmgJfOk6kGb69w5hXt9DRd0gdQCVJIHfmsyV+Of/CCeBWqjNzQ7+zWIeH3ypH+eYS3NuptTPsPEVTl6T12qZrTK2Wb9Of/VVXKvpqKulWVSNWtCKVnGHYqPGbaWHF6JYZ7Fo86GG/HdqqXbtaNYNkFaDEGlXnvsHBKWZ6fcdWGpzLasjrrvId647LytT4lZXzAuFPmH1l8VHcVlCLKgfWe+9vm+su6HQ4eeISaaxUoN18dIj7l8icEKuQ+t2ukW9XZyfQHe+KLNcNU70R0PqzNQyDIvqzF97JB72QIaMFcw63DACvxdI7ahbyt0wd3hIcaKPF6AUIfvxTauwFINVdpvCK4Fr0K2iqFgNe2qjIg88ALSmx2Ibkq6kjYkfr8K6NH4X2AVqTgTrO+30kX4vSMMZVAt5re72uMIOIkVdHDxpVGuFr0TgHMyMVxjD3/B194a1OFP4fm6djCbZmZEEAm+kh+Rgbc6oZXa5eklJReYiVTFszBDPjCclvtEJf1zgk4ELrPf9hSW3DDZSQtEBK3a8nmi4BYWH/40E7OEo7X8kUf42uiXzHVqcDMfo2mkzmjLsccXfqfpO8BywgfQC/G74qetrDVtMBlg==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
